package pt.tecnico.blockchainist.status;

public enum InternalResponseStatus {
    
    OK,
    EXECUTED_LOCALY,
    DUPLICATE_TRANSACTION,
    BAD_USER_FORMAT,
    BAD_WALLET_FORMAT,
    WALLET_ALREADY_EXISTS,
    WALLET_NOT_FOUND,
    USER_NOT_FOUND,
    NOT_AUTHORIZED,
    REMAINING_BALANCE,
    INSUFFICIENT_BALANCE,
    NEGATIVE_AMOUNT,
    WRONG_ORGANIZATION,
    UNKNOWN;

}

